<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Sublime Text 2 tmLanguage File -->
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>s19</string>
		<string>s28</string>
		<string>s37</string>
		<string>s</string>
		<string>s1</string>
		<string>s2</string>
		<string>s3</string>
		<string>sx</string>
		<string>srec</string>
		<string>mot</string>
	</array>
	<key>name</key>
	<string>SREC</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.record.begin</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.record.byte-count</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.record.address</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.constant.record.data</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>comment.block.record.checksum</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^([sS][0159])([a-fA-F\d]{2})([a-fA-F\d]{4})([a-fA-F\d]*?)([a-fA-F\d]{2})$</string>
			<key>scope</key>
			<string>s0159.record</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.record.begin</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.record.byte-count</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.record.address</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.constant.record.data</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>comment.block.record.checksum</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^([sS][268])([a-fA-F\d]{2})([a-fA-F\d]{6})([a-fA-F\d]*?)([a-fA-F\d]{2})$</string>
			<key>scope</key>
			<string>s268.record</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.record.begin</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.record.byte-count</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.record.address</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.constant.record.data</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>comment.block.record.checksum</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^([sS][37])([a-fA-F\d]{2})([a-fA-F\d]{8})([a-fA-F\d]*?)([a-fA-F\d]{2})$</string>
			<key>scope</key>
			<string>s37.record</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[^sS]*</string>
			<key>name</key>
			<string>invalid.malformed-record</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[^sSa-fA-F\d\n\r]</string>
			<key>name</key>
			<string>invalid.illegal.character</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.srec</string>
</dict>
</plist>
